# -*- coding: utf-8 -*-
# ================================================================
# AUTO-GENERATED by scripts/build_embed_secrets.py — 勿手改
# 内置 AI 配置（XOR+base64 混淆，非明文）。已加入 .gitignore。
# 仅供打包进 exe；发布产物中不含任何明文密钥。
# ================================================================
_XOR_KEY = b'KP-AI-FENGSHUI-2026-PUB'


def _xor(b: bytes) -> bytes:
    return bytes(c ^ _XOR_KEY[i % len(_XOR_KEY)] for i, c in enumerate(b))


def _d(s: str) -> str:
    import base64
    return _xor(base64.b64decode(s)).decode('utf-8')


AGNES_API_URL = _d('IyRZMToXaWovNzpmNC5DV0MfV0R+NixkJhxuKkUnMWEkPCUlJUhGWV1YXg==')
AGNES_API_KEY = _d('CTVMMyxfZjYlaj0QNgN7cXxeQ2QyJyMlE24JDmJ/CAc1PgoTP0VgXAdzGTc6CQYiXhc9HQB1KCwVJQ==')
AGNES_MODEL = _d('KjdDJDoAdGt7ajUkNDpF')

# ---- 无害本地请求参数（非机密，明文默认值）----
TIMEOUT = 120
MAX_RETRIES = 2
RETRY_DELAY = 5
