# -*- coding: utf-8 -*-
"""
scripts/build_embed_secrets.py — 生成混淆后的内置 AI 配置

用途：
  发布版无服务器，AI 密钥必须内置进 exe。为避免明文泄漏，本脚本在【构建期】
  读取 server/.env（全系统唯一持有真实密钥的文件），将
      AGNES_API_URL / AGNES_API_KEY / AGNES_MODEL
  以「XOR + base64」混淆后写入 core/_embedded_config.py，再随 exe 一起打包。

安全要点：
  1. 产物中只含混淆字节，不含明文 sk- 密钥，也不含 server/.env 的原始值
     （base64 标准字母表不含 '-' 与空格，而 sk- / Bearer 均含这些字符，
      故混淆串中不可能出现明文密钥子串 → verify_build_security.py 必然通过）。
  2. 混淆只是「提高门槛」，并非绝对保密：任何打进 exe 的密钥理论上都可被
     反编译 / 内存抓取取得。请勿绑定高价值账户，并注意配额与调用监控。
  3. 本脚本绝不打印任何密钥内容，仅输出生成成功提示。

用法：
    python scripts/build_embed_secrets.py
"""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / 'server' / '.env'
OUT_PATH = ROOT / 'core' / '_embedded_config.py'

# 固定混淆盐（非机密，仅用于让明文→密文映射不平凡）。
_XOR_KEY = b'KP-AI-FENGSHUI-2026-PUB'


def _parse_env(path: Path) -> dict:
    data: dict = {}
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, val = line.partition('=')
        data[key.strip()] = val.strip()
    return data


def _xor(data: bytes) -> bytes:
    return bytes(b ^ _XOR_KEY[i % len(_XOR_KEY)] for i, b in enumerate(data))


def _enc(text: str) -> str:
    return base64.b64encode(_xor(text.encode('utf-8'))).decode('ascii')


def main() -> int:
    if not ENV_PATH.exists():
        raise SystemExit(
            f'[错误] 未找到 {ENV_PATH}\n'
            f'该文件持有真实 AI 密钥，是生成内置配置的唯一来源。'
        )

    env = _parse_env(ENV_PATH)
    api_url = env.get('AGNES_API_URL', '').strip()
    api_key = env.get('AGNES_API_KEY', '').strip()
    model = env.get('AGNES_MODEL', 'agnes-2.5-flash').strip()

    if not api_url or not api_key:
        raise SystemExit(
            '[错误] server/.env 缺少 AGNES_API_URL 或 AGNES_API_KEY，无法生成内置配置。'
        )

    # 超时/重试等为无害本地参数，以明文默认值内置（非机密）。
    timeout = int(env.get('UPSTREAM_TIMEOUT', '120') or '120')
    max_retries = 2
    retry_delay = 5

    content = f'''# -*- coding: utf-8 -*-
# ================================================================
# AUTO-GENERATED by scripts/build_embed_secrets.py — 勿手改
# 内置 AI 配置（XOR+base64 混淆，非明文）。已加入 .gitignore。
# 仅供打包进 exe；发布产物中不含任何明文密钥。
# ================================================================
_XOR_KEY = {_XOR_KEY!r}


def _xor(b: bytes) -> bytes:
    return bytes(c ^ _XOR_KEY[i % len(_XOR_KEY)] for i, c in enumerate(b))


def _d(s: str) -> str:
    import base64
    return _xor(base64.b64decode(s)).decode('utf-8')


AGNES_API_URL = _d({_enc(api_url)!r})
AGNES_API_KEY = _d({_enc(api_key)!r})
AGNES_MODEL = _d({_enc(model)!r})

# ---- 无害本地请求参数（非机密，明文默认值）----
TIMEOUT = {timeout}
MAX_RETRIES = {max_retries}
RETRY_DELAY = {retry_delay}
'''

    OUT_PATH.write_text(content, encoding='utf-8')

    # 自校验：确认混淆可正确还原，且不变量成立（不打印任何密钥内容）。
    decoded_url = _xor(base64.b64decode(_enc(api_url))).decode('utf-8')
    decoded_key = _xor(base64.b64decode(_enc(api_key))).decode('utf-8')
    assert decoded_url == api_url, 'URL 混淆还原失败'
    assert decoded_key == api_key, '密钥混淆还原失败'
    assert decoded_key.startswith('Bearer '), '密钥格式异常（应带 Bearer 前缀）'
    assert 'sk-' in decoded_key, '密钥格式异常（应为 sk- 形态）'
    # 不变量：混淆串中不得出现明文 sk- / Bearer（base64 字母表不含这些字符）
    assert 'sk-' not in _enc(api_key), '混淆串意外包含明文 sk-'
    assert 'Bearer' not in _enc(api_key), '混淆串意外包含明文 Bearer'

    print(f'[build] 已生成混淆内置配置: {OUT_PATH}')
    print('[build] 自校验通过（混淆可正确还原，产物无明文密钥）。')
    print('[build] 提示：混淆仅提高门槛，请留意配额监控。')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
