# -*- mode: python ; coding: utf-8 -*-
"""风水排盘专业工具 - 便携版打包配置 (自动生成)"""
import os

block_cipher = None

_project_root = r'D:\PythonProject\KP-AI-FENGSHUI'
_pyside6_path = r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages'

a = Analysis(
    [r'D:\PythonProject\KP-AI-FENGSHUI\main.py'],
    pathex=['D:\\anaconda3\\Lib\\site-packages', 'F:\\AppData\\Roaming\\Python\\Python313\\site-packages', 'D:\\PythonProject\\KP-AI-FENGSHUI', 'D:\\PythonProject\\KP-AI-FENGSHUI\\scripts'],
    binaries=[
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\msvcp140.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\msvcp140_1.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\msvcp140_2.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\msvcp140_codecvt_ids.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\msvcp140_atomic_wait.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\vcruntime140.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\vcruntime140_1.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\concrt140.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\vcruntime140_threads.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\vccorlib140.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\libssl-3-x64.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\libcrypto-3-x64.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\_ssl.pyd', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icudt.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icudt73.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icuin.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icuin73.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icuio.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icuio73.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icutest.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icutest73.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icutu.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icutu73.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icuuc.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\icuuc73.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qdirect2d.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qminimal.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qoffscreen.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qwindows.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DAnimation_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DCore_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DExtras_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DInput_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DLogic_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DQuick_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DQuickAnimation_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DQuickExtras_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DQuickInput_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DQuickRender_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DQuickScene2D_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt53DRender_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Bluetooth_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Bodymovin_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Charts_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Concurrent_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Core_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5DataVisualization_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5DBus_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Designer_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5DesignerComponents_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Gamepad_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Gui_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Help_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Location_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Multimedia_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5MultimediaQuick_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5MultimediaWidgets_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Network_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5NetworkAuth_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Nfc_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5OpenGL_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Pdf_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5PdfWidgets_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Positioning_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5PositioningQuick_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5PrintSupport_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Purchasing_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Qml_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QmlModels_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QmlWorkerScript_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Quick3D_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Quick3DAssetImport_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Quick3DRender_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Quick3DRuntimeRender_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Quick3DUtils_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Quick_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QuickControls2_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QuickParticles_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QuickShapes_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QuickTemplates2_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QuickTest_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5QuickWidgets_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5RemoteObjects_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Script_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5ScriptTools_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Scxml_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Sensors_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5SerialBus_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5SerialPort_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Sql_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Svg_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Test_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5TextToSpeech_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5VirtualKeyboard_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5WebChannel_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5WebEngine_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5WebEngineCore_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5WebEngineWidgets_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5WebSockets_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5WebView_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Widgets_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5WinExtras_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5Xml_conda.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\Qt5XmlPatterns_conda.dll', '.'),

        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\Shiboken.pyd', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\shiboken6.abi3.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DAnimation.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DCore.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DExtras.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DInput.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DLogic.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuickAnimation.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuickExtras.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuickInput.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuickLogic.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuickRender.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuickScene2D.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DQuickScene3D.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt63DRender.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Bluetooth.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6CanvasPainter.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Charts.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6ChartsQml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Concurrent.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Core.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6DataVisualization.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6DataVisualizationQml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6DBus.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Designer.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6DesignerComponents.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Graphs.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6GraphsWidgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Gui.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Help.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6HttpServer.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsAnimation.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsFolderListModel.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsPlatform.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsQmlModels.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsSettings.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsSharedImage.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsStyleKit.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsStyleKitImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsSynchronizer.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LabsWavefrontMesh.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Location.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Lottie.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LottieVectorImageGenerator.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6LottieVectorImageHelpers.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Multimedia.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6MultimediaQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6MultimediaWidgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Network.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6NetworkAuth.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Nfc.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6OpenGL.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6OpenGLWidgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Pdf.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6PdfQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6PdfWidgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Positioning.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6PositioningQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6PrintSupport.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Qml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlCompiler.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlCore.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlLocalStorage.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlMeta.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlModels.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlNetwork.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlWorkerScript.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QmlXmlListModel.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3D.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DAssetImport.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DAssetUtils.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DEffects.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DGlslParser.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DHelpers.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DHelpersImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DIblBaker.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DParticleEffects.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DParticles.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DRuntimeRender.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DSpatialAudio.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DUtils.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Quick3DXr.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2Basic.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2BasicStyleImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2FluentWinUI3StyleImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2Fusion.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2FusionStyleImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2Imagine.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2ImagineStyleImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2Impl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2Material.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2MaterialStyleImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2Universal.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2UniversalStyleImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickControls2WindowsStyleImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickDialogs2.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickDialogs2QuickImpl.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickDialogs2Utils.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickEffects.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickLayouts.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickParticles.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickShapes.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickTemplates2.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickTest.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickTimeline.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickTimelineBlendTrees.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickVectorImage.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickVectorImageGenerator.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickVectorImageHelpers.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6QuickWidgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6RemoteObjects.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6RemoteObjectsQml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Scxml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6ScxmlQml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Sensors.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6SensorsQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6SerialBus.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6SerialPort.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6ShaderTools.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6SpatialAudio.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Sql.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6StateMachine.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6StateMachineQml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Svg.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6SvgWidgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Test.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6TextToSpeech.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6UiTools.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6VirtualKeyboard.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6VirtualKeyboardQml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6VirtualKeyboardSettings.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebChannel.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebChannelQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebEngineCore.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebEngineQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebEngineQuickDelegatesQml.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebEngineWidgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebSockets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebView.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6WebViewQuick.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Widgets.dll', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt6Xml.dll', '.'),

    ],
    datas=[
        (r'D:\PythonProject\KP-AI-FENGSHUI\assets\favicon.ico', '.'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\database', 'database'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\data', 'data'),
        (r'D:\anaconda3\Lib\site-packages\certifi\cacert.pem', 'certifi'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\assetimporters\assimp.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\canbus\qtpassthrucanbus.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\canbus\qtpeakcanbus.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\canbus\qtsysteccanbus.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\canbus\qttinycanbus.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\canbus\qtvectorcanbus.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\canbus\qtvirtualcanbus.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\designer\PySidePlugin.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\designer\qaxwidget.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\designer\qquickwidget.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\designer\qwebengineview.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\generic\qtuiotouchplugin.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\geometryloaders\defaultgeometryloader.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\geometryloaders\gltfgeometryloader.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\geoservices\qtgeoservices_itemsoverlay.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\geoservices\qtgeoservices_osm.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\iconengines\qsvgicon.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qgif.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qicns.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qico.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qjpeg.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qpdf.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qsvg.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qtga.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qtiff.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qwbmp.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\imageformats\qwebp.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\multimedia\ffmpegmediaplugin.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\multimedia\windowsmediaplugin.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\networkinformation\qnetworklistmanager.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforminputcontexts\qtvirtualkeyboardplugin.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qdirect2d.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qminimal.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qoffscreen.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\platforms\qwindows.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\position\qtposition_nmea.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\position\qtposition_positionpoll.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\position\qtposition_winrt.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmllint\qdslintplugin.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmllint\quicklintplugin.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_debugger.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_inspector.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_local.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_messages.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_native.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_nativedebugger.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_preview.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_profiler.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_quick3dprofiler.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_quickeventreplay.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_quickprofiler.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_server.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\qmltooling\qmldbg_tcp.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\renderers\openglrenderer.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\renderers\rhirenderer.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\renderplugins\scene2d.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sceneparsers\assimpsceneimport.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sceneparsers\gltfsceneexport.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sceneparsers\gltfsceneimport.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\scxmldatamodel\qscxmlecmascriptdatamodel.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sensors\qtsensors_generic.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sensors\qtsensors_winrt.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sqldrivers\qsqlibase.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sqldrivers\qsqlite.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sqldrivers\qsqlmimer.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sqldrivers\qsqloci.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sqldrivers\qsqlodbc.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\sqldrivers\qsqlpsql.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\styles\qmodernwindowsstyle.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\texttospeech\qtexttospeech_mock.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\texttospeech\qtexttospeech_sapi.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\texttospeech\qtexttospeech_winrt.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\tls\qcertonlybackend.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\tls\qopensslbackend.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\tls\qschannelbackend.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\vectorimageformats\qlottievectorimage.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\webview\qtwebview_webengine.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\plugins\webview\qtwebview_webview2.dll', 'PySide6/plugins'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\__init__.py', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt3DAnimation.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt3DCore.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt3DExtras.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt3DInput.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt3DLogic.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\Qt3DRender.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtAxContainer.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtBluetooth.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtCanvasPainter.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtCharts.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtConcurrent.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtCore.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtDataVisualization.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtDBus.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtDesigner.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtGraphs.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtGraphsWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtGui.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtHelp.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtHttpServer.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtLocation.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtMultimedia.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtMultimediaWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtNetwork.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtNetworkAuth.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtNfc.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtOpenGL.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtOpenGLWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtPdf.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtPdfWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtPositioning.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtPrintSupport.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtQml.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtQuick.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtQuick3D.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtQuickControls2.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtQuickTest.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtQuickWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtRemoteObjects.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtScxml.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtSensors.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtSerialBus.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtSerialPort.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtSpatialAudio.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtSql.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtStateMachine.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtSvg.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtSvgWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtTest.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtTextToSpeech.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtUiTools.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtWebChannel.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtWebEngineCore.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtWebEngineQuick.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtWebEngineWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtWebSockets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtWebView.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtWidgets.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\PySide6\QtXml.pyd', 'PySide6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\concrt140.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\msvcp140.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\msvcp140_1.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\msvcp140_2.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\msvcp140_codecvt_ids.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\py.typed', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\Shiboken.pyd', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\shiboken6.abi3.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\vcamp140.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\vccorlib140.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\vcomp140.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\vcruntime140.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\vcruntime140_1.dll', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\_config.py', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\_git_shiboken_module_version.py', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\__init__.py', 'shiboken6/'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\__pycache__\_config.cpython-313.pyc', 'shiboken6/__pycache__'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\__pycache__\_git_shiboken_module_version.cpython-313.pyc', 'shiboken6/__pycache__'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\__pycache__\__init__.cpython-313.pyc', 'shiboken6/__pycache__'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\lib\cmake\Shiboken6\Shiboken6Config.abi3.cmake', 'shiboken6/lib/cmake/Shiboken6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\lib\cmake\Shiboken6\Shiboken6Config.cmake', 'shiboken6/lib/cmake/Shiboken6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\lib\cmake\Shiboken6\Shiboken6ConfigVersion.cmake', 'shiboken6/lib/cmake/Shiboken6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\lib\cmake\Shiboken6\Shiboken6Targets-release.cmake', 'shiboken6/lib/cmake/Shiboken6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\lib\cmake\Shiboken6\Shiboken6Targets.cmake', 'shiboken6/lib/cmake/Shiboken6'),
        (r'D:\PythonProject\KP-AI-FENGSHUI\pyside6_packages\shiboken6\lib\cmake\Shiboken6\ShibokenHelpers.cmake', 'shiboken6/lib/cmake/Shiboken6'),
    ],
    hiddenimports=[
        'core.path_utils',
        'core.secure_log',
        'core.device_identity',
        'core.sqlite_db',
        'core.log_handler',
        'core.knowledge.analysis_storage',
        'core.ai_cache',
        'core.database_manager',
        'core.bazi.bazi_calculator',
        'core.bazi.bazi_types',
        'core.calendar_utils',
        'core.ganzhi_constants',
        'core.knowledge.data_validator',
        'core.knowledge.data_integration',
        'core.bazi.geju_analyzer',
        'core.divination.hexagram_analyzer',
        'core.divination.hexagram_data',
        'core.knowledge.knowledge_base',
        'core.divination.liuren',
        'core.location_db',
        'core.lunar_converter',
        'core.divination.meihua',
        'core.bazi.mingli',
        'core.bazi.shishen',
        'core.bazi.wuxing',
        'core.bazi.yuncheng',
        'core.bazi.yunshi',
        'core.bazi._baazi_compat',
        'ui.main_window',
        'ui.styles',
        'ui.components.settings_dialog',
        'ui.components.about_dialog',
        'ui.components.input_panel',
        'ui.components.result_panel',
        'ui.components.meihua_input',
        'ui.components.meihua_result_panel',
        'ui.components.liuren_input',
        'ui.components.liuren_result_panel',
        'ui.components.ai_analysis_worker',
        'ui.components.collapsible_card',
        'ui.components.export_dialog',
        'ui.export.base_exporter',
        'ui.export.csv_exporter',
        'ui.export.excel_exporter',
        'ui.export.pdf_exporter',
        'core.app_version',
        'api.agnes_client',
        'core.ai_config',
        'core.local_settings',
        'lunarcalendar',
        'bcrypt',
        'openpyxl',
        'reportlab',
        'reportlab.graphics',
        'reportlab.lib.colors',
        '_ssl', 'ssl', 'certifi', 'certifi.core',
        'urllib3.util.ssl_',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[r'D:\PythonProject\KP-AI-FENGSHUI\scripts\pyi_rth_ssl.py', r'D:\PythonProject\KP-AI-FENGSHUI\scripts\pyi_rth_pyside6_qt6.py', r'D:\PythonProject\KP-AI-FENGSHUI\scripts\pyi_rth_dll_fix.py'],
    excludes=['PyQt5', 'PyQt6', 'PIL', 'notebook', 'jinja2', 'tkinter',
              'server', 'server.app', 'core._embedded_config'],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    name='风水排盘专业工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=os.path.join(_project_root, 'version_info.txt'),
    icon=os.path.join(_project_root, 'assets', 'favicon.ico'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    name='风水排盘专业工具',
)
